
const ENUM_MAPPINGS = {
    combustivel: {
        'gasolina': 'GASOLINA',
        'etanol': 'ETANOL',
        'flex': 'FLEX',
        'diesel': 'DIESEL',
        'elétrico': 'ELETRICO',
        'eletrico': 'ELETRICO',
        'híbrido': 'HIBRIDO',
        'hibrido': 'HIBRIDO',
        'gnv': 'GNV'
    },
    cambio: {
        'manual': 'MANUAL',
        'automático': 'AUTOMATICO',
        'automatico': 'AUTOMATICO',
        'semi-automático': 'SEMI_AUTOMATICO',
        'semi automatico': 'SEMI_AUTOMATICO',
        'semiautomatico': 'SEMI_AUTOMATICO',
        'cvt': 'CVT'
    },
    carroceria: {
        'hatch': 'HATCH',
        'sedã': 'SEDAN',
        'sedan': 'SEDAN',
        'suv': 'SUV',
        'picape': 'PICAPE',
        'coupé': 'COUPE',
        'coupe': 'COUPE',
        'conversível': 'CONVERSIVEL',
        'conversivel': 'CONVERSIVEL',
        'perua': 'PERUA',
        'minivan': 'MINIVAN',
        'van': 'VAN',
        'buggy': 'BUGGY',
        'offroad': 'OFFROAD'
    },
    categoria: {
        'hyper car': 'HYPERCAR',
        'hipercarro': 'HYPERCAR',
        'supercar': 'SUPERCAR',
        'super car': 'SUPERCAR',
        'supercarro': 'SUPERCAR',
        'esportivo': 'SPORTS_CAR',
        'esporte': 'SPORTS_CAR',
        'sports': 'SPORTS_CAR',
        'sports car': 'SPORTS_CAR',
        'carro esportivo': 'SPORTS_CAR',
        'muscle classico': 'CLASSIC_MUSCLE',
        'muscle clássico': 'CLASSIC_MUSCLE',
        'muscle': 'CLASSIC_MUSCLE',
        'muscle car': 'CLASSIC_MUSCLE',
        'carro muscle': 'CLASSIC_MUSCLE',
        'muscle moderno': 'MODERN_MUSCLE',
        'modern muscle': 'MODERN_MUSCLE',
        'retro super': 'RETRO_SUPER',
        'retro': 'RETRO_SUPER',
        'super retro': 'RETRO_SUPER',
        'drift': 'DRIFT_CAR',
        'drift car': 'DRIFT_CAR',
        'carro drift': 'DRIFT_CAR',
        'track toy': 'TRACK_TOY',
        'brinquedo pista': 'TRACK_TOY',
        'offroad': 'OFFROAD',
        'fora de estrada': 'OFFROAD',
        '4x4': 'OFFROAD',
        'buggy': 'BUGGY',
        'pickup 4x4': 'PICKUP_4X4',
        'picape 4x4': 'PICKUP_4X4',
        'caminhonete': 'PICKUP_4X4',
        'suv': 'SUV',
        'utilitaire': 'SUV',
        'hot hatch': 'HOT_HATCH',
        'hatch esportivo': 'HOT_HATCH',
        'hatch quente': 'HOT_HATCH',
        'saloon': 'SALOON',
        'sedan': 'SALOON',
        'sedã': 'SALOON',
        'gt': 'GT',
        'grand tourer': 'GT',
        'gran turismo': 'GT',
        'rally': 'RALLY',
        'rali': 'RALLY',
        'concept': 'CONCEPT',
        'conceito': 'CONCEPT',
        'carro conceito': 'CONCEPT',
        
        // Adicionando variações em português
        'hipercarro': 'HYPERCAR',
        'superesportivo': 'SPORTS_CAR',
        'carro de corrida': 'TRACK_TOY',
        'brinquedo de pista': 'TRACK_TOY',
        'caminhonete 4x4': 'PICKUP_4X4',
        'utilitário esportivo': 'SUV',
        'hatchback': 'HOT_HATCH',
        'cupê': 'COUPE',
        'perua': 'PERUA',
        'station wagon': 'PERUA',
        'minivan': 'MINIVAN',
        'van': 'VAN'
    }
};

module.exports = ENUM_MAPPINGS;